version: '3.7'


services:
  frontend:
    container_name: ${APP_FRONTEND_NAME}
    build:
      context: frontend
      args:
        - APP_BACKEND_HOST=${APP_BACKEND_HOST}
        - APP_BACKEND_PORT=${APP_BACKEND_PORT}
    ports:
      - ${APP_FRONTEND_PORT}:80
    networks:
      - formalivrenet
    env_file:
      - ./.env

  backend:
    container_name: ${APP_BACKEND_NAME}
    build:
      context: backend
    ports:
      - ${APP_BACKEND_PORT}:${APP_BACKEND_PORT}
    networks:
      - formalivrenet
    env_file:
      - ./.env

  database:
    image: postgres:15.1-bullseye
    container_name: ${APP_DATABASE_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - formalivrenet
    volumes:
      - ./.volumes/postgres/log:/var/log/postgresql
      - ./.volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4:2022-11-17-1
    container_name: ${PGADMIN_NAME}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - formalivrenet
    env_file:
      - ./.env


networks:
  formalivrenet:
    external:
      name: formalivrenet
